server:
  port: 8086
spring:
  application:
    name: stockNacos
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public